package com.nicefish.mapper;

import com.nicefish.model.SysParams;

public interface SysParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    int insert(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    int insertSelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    SysParams selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysParams record);
}