package com.nicefish.mapper;

import com.nicefish.model.Upload;

public interface UploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    int insert(Upload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    int insertSelective(Upload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    Upload selectByPrimaryKey(String upId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Upload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Upload record);
}