package com.nicefish.model;

import java.util.Date;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_ID
     *
     * @mbggenerated
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.P_ID
     *
     * @mbggenerated
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_IP
     *
     * @mbggenerated
     */
    private String commentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_TIME
     *
     * @mbggenerated
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.POST_ID
     *
     * @mbggenerated
     */
    private String postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CONTENT
     *
     * @mbggenerated
     */
    private String content;
}