package com.nicefish.model;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    private String permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_CODE
     *
     * @mbggenerated
     */
    private String permissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_DESC
     *
     * @mbggenerated
     */
    private String permissionDesc;
}