package com.nicefish.model;

import java.util.Date;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.POST_ID
     *
     * @mbggenerated
     */
    private String postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.POST_TITLE
     *
     * @mbggenerated
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.POST_TIME
     *
     * @mbggenerated
     */
    private Date postTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.ORIGINAL_URL
     *
     * @mbggenerated
     */
    private String originalUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.POST_TYPE
     *
     * @mbggenerated
     */
    private Integer postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.LAST_MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.READ_TIMES
     *
     * @mbggenerated
     */
    private Integer readTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.LIKED_TIMES
     *
     * @mbggenerated
     */
    private Integer likedTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.COMMENT_TIMES
     *
     * @mbggenerated
     */
    private Integer commentTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.ENABLE_COMMENT
     *
     * @mbggenerated
     */
    private Integer enableComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.POST_CONTENT
     *
     * @mbggenerated
     */
    private String postContent;
}