package com.nicefish.model;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class SysParams {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.PARAM_KEY
     *
     * @mbg.generated
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.PARAM_VALUE
     *
     * @mbg.generated
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.PARAM_DESC
     *
     * @mbg.generated
     */
    private String paramDesc;
}