package com.nicefish.model;

import java.util.Date;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Upload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.UP_ID
     *
     * @mbg.generated
     */
    private String upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.UP_TIME
     *
     * @mbg.generated
     */
    private Date upTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_NAME
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_TYPE
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_WIDTH
     *
     * @mbg.generated
     */
    private Integer fileWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_HEIGHT
     *
     * @mbg.generated
     */
    private Integer fileHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_SIZE
     *
     * @mbg.generated
     */
    private Float fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.DISPLAY_ORDER
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_MODULE
     *
     * @mbg.generated
     */
    private Integer fileModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.FILE_DESC
     *
     * @mbg.generated
     */
    private String fileDesc;
}